const JOBS_TIMINGS = require('./jobs_timings');
let d = new Date();
let currentYear = d.getUTCFullYear();
let currentMonth = d.getUTCMonth()
let currentDate = d.getUTCDate();

const jobsData = [
    {
        "scheduleID": "1000073",
        "jobID": 1301,
        "workerSNO": "S2615110",
        "job_description": "Attach Body Fittings",
        "orderid": "000054286100",
        "order_number": "000054286100",
        "start_time": 1676334600,
        "end_time": 1676340000,
        "job_status": "Not Started",
        "isTravelled": false,
        "criticalRatio": null,
        "criticalPath": 0,
        "isConstrained": false,
        "constraints": 0,
        "machineID": null,
        "claim_dt": null,
        "end_dt": null,
        "jobType": "Brush Seal | Pressure Floor",
        "time_elapsed": "0",
        "estimated_duration": "90",
        "lineUnit": "01847",
        "lineNumber": "Line 1 (1 day)",
        "actualEndtime": null,
        "actualStarttime": 1676334600,
        "assigned_mechanics": 1,
        "required_mechanics": 1,
        "subarea": "11 Wingbox",
        "si": "IP-0000045139",
        "mechanic_claimTime": null,
        "mechanic_completeTime": null,
        "materialNumber": "314T4012-120",
        "durationwithBreaks": "90", 
        "faultCode" : "FC001"
},
    {
        "scheduleID": "1000074",
        "jobID": 1302,
        "workerSNO": "S2615110",
        "job_description": "Attach Breakring",
        "orderid": "000054286110",
        "order_number": "000054286110",
        "start_time": 1676341800,
        "end_time": 1676349000,
        "job_status": "Not Started",
        "isTravelled": false,
        "criticalRatio": null,
        "criticalPath": 0,
        "isConstrained": false,
        "constraints": 0,
        "machineID": null,
        "claim_dt": null,
        "end_dt": null,
        "jobType": "Autoclave Cure",
        "time_elapsed": "0",
        "estimated_duration": "150",
        "lineUnit": "01147",
        "lineNumber": "Line 1 (1 day)",
        "actualEndtime": null,
        "actualStarttime": null,
        "assigned_mechanics": 1,
        "required_mechanics": 1,
        "subarea": "44 Berthas",
        "si": "IP-0000045140",
        "mechanic_claimTime": null,
        "mechanic_completeTime": null,
        "materialNumber": "314T4012-121",
        "durationwithBreaks": "150", 
        "faultCode" : "FC001"
    },
    {
        "scheduleID": "1000075",
        "jobID": 1303,
        "workerSNO": "S2615110",
        "job_description": "Insulation Panel Installation",
        "orderid": "000054286120",
        "order_number": "000054286120",
        "start_time": 1676349000,
        "end_time": 1676356200,
        "job_status": "Not Started",
        "isTravelled": false,
        "criticalRatio": null,
        "criticalPath": 0,
        "isConstrained": false,
        "constraints": 0,
        "machineID": null,
        "claim_dt": null,
        "end_dt": null,
        "jobType": "Layup & Bag",
        "time_elapsed": "0",
        "estimated_duration": "105",
        "lineUnit": "00147",
        "lineNumber": "Line 1 (1 day)",
        "actualEndtime": null,
        "actualStarttime": null,
        "assigned_mechanics": 1,
        "required_mechanics": 1,
        "subarea": "44 Join",
        "si": "IP-0000045141",
        "mechanic_claimTime": null,
        "mechanic_completeTime": null,
        "materialNumber": "314T4012-123",
        "durationwithBreaks": "120", 
        "faultCode" : "FC001"
},
    {
        "scheduleID": "1000076",
        "jobID": 1304,
        "workerSNO": "S2615110",
        "job_description": "Finish FWD Cargo Door Frame",
        "orderid": "000054286130",
        "order_number": "000054286130",
        "start_time": 1676356200,
        "end_time": 1676363400,
        "job_status": "Not Started",
        "isTravelled": false,
        "criticalRatio": null,
        "criticalPath": 0,
        "isConstrained": false,
        "constraints": 0,
        "machineID": null,
        "claim_dt": null,
        "end_dt": null,
        "jobType": "Bond Blast",
        "time_elapsed": "0",
        "estimated_duration": "90",
        "lineUnit": "01147",
        "lineNumber": "Line 1 (1 day)",
        "actualEndtime": null,
        "actualStarttime": null,
        "assigned_mechanics": 1,
        "required_mechanics": 1,
        "subarea": "47/48 Join",
        "si": "IP-0000045142",
        "mechanic_claimTime": null,
        "mechanic_completeTime": null,
        "materialNumber": "314T4012-124",
        "durationwithBreaks": "120", 
        "faultCode" : "FC001"
},
    {
        "scheduleID": "1000077",
        "jobID": 1305,
        "workerSNO": "S2615111",
        "job_description": "Antenna Provisions UL-HF2 46 Sect",
        "orderid": "000054286140",
        "order_number": "000054286140",
        "start_time": 1676363400,
        "end_time": 1676370600,
        "job_status": "Not Started",
        "isTravelled": false,
        "criticalRatio": null,
        "criticalPath": 0,
        "isConstrained": false,
        "constraints": 0,
        "machineID": null,
        "claim_dt": null,
        "end_dt": null,
        "jobType": "Breakout",
        "time_elapsed": "0",
        "estimated_duration": "120",
        "lineUnit": "01162",
        "lineNumber": "Line 1 (1 day)",
        "actualEndtime": null,
        "actualStarttime": null,
        "assigned_mechanics": 1,
        "required_mechanics": 1,
        "subarea": "47 Balcony",
        "si": "IP-0000045143",
        "mechanic_claimTime": null,
        "mechanic_completeTime": null,
        "materialNumber": "314T4012-121",
        "durationwithBreaks": "120", 
        "faultCode" : "FC001"
    },
    {
        "scheduleID": "1000078",
        "jobID": 1306,
        "workerSNO": "S2615111",
        "job_description": "Airstairs Sill Webs To Outer Chords",
        "orderid": "000054286150",
        "order_number": "000054286150",
        "start_time": 1676370600,
        "end_time": 1676381400,
        "job_status": "Not Started",
        "isTravelled": false,
        "criticalRatio": null,
        "criticalPath": 0,
        "isConstrained": false,
        "constraints": 0,
        "machineID": null,
        "claim_dt": null,
        "end_dt": null,
        "jobType": "Layup & Bag",
        "time_elapsed": "0",
        "estimated_duration": "180",
        "lineUnit": "09162",
        "lineNumber": "Line 1 (1 day)",
        "actualEndtime": null,
        "actualStarttime": null,
        "assigned_mechanics": 1,
        "required_mechanics": 1,
        "subarea": "47 Balcony",
        "si": "IP-0000045144",
        "mechanic_claimTime": null,
        "mechanic_completeTime": null,
        "materialNumber": "314T4012-125",
        "durationwithBreaks": "180", 
        "faultCode" : "FC001"
},
    {
        "scheduleID": "1000079",
        "jobID": 1307,
        "workerSNO": "S2615111",
        "job_description": "Airstairs Install Misc Components",
        "orderid": "000054286160",
        "order_number": "000054286160",
        "start_time": 1676381400,
        "end_time": 1676390400,
        "job_status": "Not Started",
        "isTravelled": false,
        "criticalRatio": null,
        "criticalPath": 0,
        "isConstrained": false,
        "constraints": 0,
        "machineID": null,
        "claim_dt": null,
        "end_dt": null,
        "jobType": "Autoclave Cure",
        "time_elapsed": "0",
        "estimated_duration": "135",
        "lineUnit": "08112",
        "lineNumber": "Line 1 (1 day)",
        "actualEndtime": null,
        "actualStarttime": null,
        "assigned_mechanics": 1,
        "required_mechanics": 1,
        "subarea": "11 Wingbox",
        "si": "IP-0000045145",
        "mechanic_claimTime": null,
        "mechanic_completeTime": null,
        "materialNumber": "314T4012-126",
        "durationwithBreaks": "150", 
        "faultCode" : "FC001"
    },
    {
        "scheduleID": "1000080",
        "jobID": 1316,
        "workerSNO": "S2615111",
        "job_description": "Attach Body Fittings",
        "orderid": "000054286170",
        "order_number": "000054286170",
        "start_time": 1676390400,
        "end_time": 1676395800,
        "job_status": "Not Started",
        "isTravelled": false,
        "criticalRatio": null,
        "criticalPath": 0,
        "isConstrained": false,
        "constraints": 0,
        "machineID": null,
        "claim_dt": null,
        "end_dt": null,
        "jobType": "Brush Seal | Pressure Floor",
        "time_elapsed": "0",
        "estimated_duration": "60",
        "lineUnit": "01500",
        "lineNumber": "Line 1 (1 day)",
        "actualEndtime": null,
        "actualStarttime": null,
        "assigned_mechanics": 1,
        "required_mechanics": 1,
        "subarea": "44 Berthas",
        "si": "IP-0000045146",
        "mechanic_claimTime": null,
        "mechanic_completeTime": null,
        "materialNumber": "314T4012-127",
        "durationwithBreaks": "90", 
        "faultCode" : "FC001"
},
    {
        "scheduleID": "1000081",
        "jobID": 1308,
        "workerSNO": "S2615112",
        "job_description": "Attach Breakring",
        "orderid": "000054286180",
        "order_number": "000054286180",
        "start_time": 1676363400,
        "end_time": 1676372400,
        "job_status": "Not Started",
        "isTravelled": false,
        "criticalRatio": null,
        "criticalPath": 0,
        "isConstrained": false,
        "constraints": 0,
        "machineID": null,
        "claim_dt": null,
        "end_dt": null,
        "jobType": "Autoclave Cure",
        "time_elapsed": "0",
        "estimated_duration": "150",
        "lineUnit": "07104",
        "lineNumber": "Line 1 (1 day)",
        "actualEndtime": null,
        "actualStarttime": null,
        "assigned_mechanics": 1,
        "required_mechanics": 1,
        "subarea": "44 Join",
        "si": "IP-0000045147",
        "mechanic_claimTime": null,
        "mechanic_completeTime": null,
        "materialNumber": "514T4012-121",
        "durationwithBreaks": "150", 
        "faultCode" : "FC001"
},
    {
        "scheduleID": "1000082",
        "jobID": 1309,
        "workerSNO": "S2615112",
        "job_description": "Insulation Panel Installation",
        "orderid": "000054286190",
        "order_number": "000054286190",
        "start_time": 1676372400,
        "end_time": 1676379600,
        "job_status": "Not Started",
        "isTravelled": false,
        "criticalRatio": null,
        "criticalPath": 0,
        "isConstrained": false,
        "constraints": 0,
        "machineID": null,
        "claim_dt": null,
        "end_dt": null,
        "jobType": "Layup & Bag",
        "time_elapsed": "0",
        "estimated_duration": "120",
        "lineUnit": "07104",
        "lineNumber": "Line 1 (1 day)",
        "actualEndtime": null,
        "actualStarttime": null,
        "assigned_mechanics": 1,
        "required_mechanics": 1,
        "subarea": "47/48 Join",
        "si": "IP-0000045148",
        "mechanic_claimTime": null,
        "mechanic_completeTime": null,
        "materialNumber": "714T4012-125",
        "durationwithBreaks": "120", 
        "faultCode" : "FC001"
 },
    {
        "scheduleID": "1000083",
        "jobID": 1310,
        "workerSNO": "S2615112",
        "job_description": "Antenna Provisions UL-HF2 46 Sect",
        "orderid": "000054286200",
        "order_number": "000054286200",
        "start_time": 1676379600,
        "end_time": 1676390400,
        "job_status": "Not Started",
        "isTravelled": false,
        "criticalRatio": null,
        "criticalPath": 0,
        "isConstrained": false,
        "constraints": 0,
        "machineID": null,
        "claim_dt": null,
        "end_dt": null,
        "jobType": "Breakout",
        "time_elapsed": "0",
        "estimated_duration": "135",
        "lineUnit": "01807",
        "lineNumber": "Line 1 (1 day)",
        "actualEndtime": null,
        "actualStarttime": null,
        "assigned_mechanics": 1,
        "required_mechanics": 1,
        "subarea": "47 Balcony",
        "si": "IP-0000045149",
        "mechanic_claimTime": null,
        "mechanic_completeTime": null,
        "materialNumber": "314T4018-121",
        "durationwithBreaks": "180", 
        "faultCode" : "FC001"
},
    {
        "scheduleID": "1000084",
        "jobID": 1311,
        "workerSNO": "S2615112",
        "job_description": "Finish FWD Cargo Door Frame",
        "orderid": "000054286210",
        "order_number": "000054286210",
        "start_time": 1676390400,
        "end_time": 1676395800,
        "job_status": "Not Started",
        "isTravelled": false,
        "criticalRatio": null,
        "criticalPath": 0,
        "isConstrained": false,
        "constraints": 0,
        "machineID": null,
        "claim_dt": null,
        "end_dt": null,
        "jobType": "Bond Blast",
        "time_elapsed": "0",
        "estimated_duration": "90",
        "lineUnit": "01807",
        "lineNumber": "Line 1 (1 day)",
        "actualEndtime": null,
        "actualStarttime": null,
        "assigned_mechanics": 1,
        "required_mechanics": 1,
        "subarea": "11 Wingbox",
        "si": "IP-0000045150",
        "mechanic_claimTime": null,
        "mechanic_completeTime": null,
        "materialNumber": "314T4019-121",
        "durationwithBreaks": "90", 
        "faultCode" : "FC001"
},
    {
        "scheduleID": "1000085",
        "jobID": 1312,
        "workerSNO": "S2615113",
        "job_description": "Antenna Provisions UL-HF2 46 Sect",
        "orderid": "000054286220",
        "order_number": "000054286220",
        "start_time": 1676395800,
        "end_time": 1676403000,
        "job_status": "Not Started",
        "isTravelled": false,
        "criticalRatio": null,
        "criticalPath": 0,
        "isConstrained": false,
        "constraints": 0,
        "machineID": null,
        "claim_dt": null,
        "end_dt": null,
        "jobType": "Layup & Bag",
        "time_elapsed": "0",
        "estimated_duration": "120",
        "lineUnit": "01847",
        "lineNumber": "Line 1 (1 day)",
        "actualEndtime": null,
        "actualStarttime": null,
        "assigned_mechanics": 1,
        "required_mechanics": 1,
        "subarea": "44 Berthas",
        "si": "IP-0000045151",
        "mechanic_claimTime": null,
        "mechanic_completeTime": null,
        "materialNumber": "414T4012-121",
        "durationwithBreaks": "120", 
        "faultCode" : "FC001"
},
    {
        "scheduleID": "1000086",
        "jobID": 1313,
        "workerSNO": "S2615113",
        "job_description": "Airstairs Sill Webs To Outer Chords",
        "orderid": "000054286230",
        "order_number": "000054286230",
        "start_time": 1676403000,
        "end_time": 1676412000,
        "job_status": "Not Started",
        "isTravelled": false,
        "criticalRatio": null,
        "criticalPath": 0,
        "isConstrained": false,
        "constraints": 0,
        "machineID": null,
        "claim_dt": null,
        "end_dt": null,
        "jobType": "Layup & Bag",
        "time_elapsed": "0",
        "estimated_duration": "135",
        "lineUnit": "01823",
        "lineNumber": "Line 1 (1 day)",
        "actualEndtime": null,
        "actualStarttime": null,
        "assigned_mechanics": 1,
        "required_mechanics": 1,
        "subarea": "44 Join",
        "si": "IP-0000045152",
        "mechanic_claimTime": null,
        "mechanic_completeTime": null,
        "materialNumber": "614T4012-121",
        "durationwithBreaks": "150", 
        "faultCode" : "FC001"
    },
    {
        "scheduleID": "1000087",
        "jobID": 1314,
        "workerSNO": "S2615113",
        "job_description": "Airstairs Install Misc Components",
        "orderid": "000054286240",
        "order_number": "000054286240",
        "start_time": 1676412000,
        "end_time": 1676415600,
        "job_status": "Not Started",
        "isTravelled": false,
        "criticalRatio": null,
        "criticalPath": 0,
        "isConstrained": false,
        "constraints": 0,
        "machineID": null,
        "claim_dt": null,
        "end_dt": null,
        "jobType": "Autoclave Cure",
        "time_elapsed": "0",
        "estimated_duration": "60",
        "lineUnit": "01892",
        "lineNumber": "Line 1 (1 day)",
        "actualEndtime": null,
        "actualStarttime": null,
        "assigned_mechanics": 1,
        "required_mechanics": 1,
        "subarea": "47/48 Join",
        "si": "IP-0000045135",
        "mechanic_claimTime": null,
        "mechanic_completeTime": null,
        "materialNumber": "714T4012-126",
        "durationwithBreaks": "60", 
        "faultCode" : "FC001"
},
    {
        "scheduleID": "1000088",
        "jobID": 1315,
        "workerSNO": "S2615113",
        "job_description": "Attach Body Fittings",
        "orderid": "000054286250",
        "order_number": "000054286250",
        "start_time": 1676415600,
        "end_time": 1676421000,
        "job_status": "Not Started",
        "isTravelled": false,
        "criticalRatio": null,
        "criticalPath": 0,
        "isConstrained": false,
        "constraints": 0,
        "machineID": null,
        "claim_dt": null,
        "end_dt": null,
        "jobType": "Brush Seal | Pressure Floor",
        "time_elapsed": "0",
        "estimated_duration": "60",
        "lineUnit": "01847",
        "lineNumber": "Line 1 (1 day)",
        "actualEndtime": null,
        "actualStarttime": null,
        "assigned_mechanics": 1,
        "required_mechanics": 1,
        "subarea": "47 Balcony",
        "si": "IP-0000045160",
        "mechanic_claimTime": null,
        "mechanic_completeTime": null,
        "materialNumber": "914T4012-121",
        "durationwithBreaks": "90", 
        "faultCode" : "FC001"
    }  
];

for(let i=0; i<jobsData.length; i++){
    if(JOBS_TIMINGS[i]["start_time"] >= "00:00:01" && JOBS_TIMINGS[i]["start_time"] <= "08:01:00"){
        let currentDateStart = currentDate + 1;
        jobsData[i].start_time = new Date(currentYear, currentMonth, currentDateStart, JOBS_TIMINGS[i]["start_time"].split(':')[0],JOBS_TIMINGS[i]["start_time"].split(':')[1],JOBS_TIMINGS[i]["start_time"].split(':')[2]).getTime();
    }
    else{
        jobsData[i].start_time = new Date(currentYear, currentMonth, currentDate, JOBS_TIMINGS[i]["start_time"].split(':')[0],JOBS_TIMINGS[i]["start_time"].split(':')[1],JOBS_TIMINGS[i]["start_time"].split(':')[2]).getTime();
    }
    if(JOBS_TIMINGS[i]["end_time"] >= "00:00:01" && JOBS_TIMINGS[i]["end_time"] <= "08:01:00"){
        let currentDateEnd = currentDate + 1;
        jobsData[i].end_time = new Date(currentYear, currentMonth, currentDateEnd, JOBS_TIMINGS[i]["end_time"].split(':')[0],JOBS_TIMINGS[i]["end_time"].split(':')[1],JOBS_TIMINGS[i]["end_time"].split(':')[2]).getTime();
    }
    else{
        jobsData[i].end_time = new Date(currentYear, currentMonth, currentDate, JOBS_TIMINGS[i]["end_time"].split(':')[0],JOBS_TIMINGS[i]["end_time"].split(':')[1],JOBS_TIMINGS[i]["end_time"].split(':')[2]).getTime();
    }
    jobsData[i].estimated_duration = JOBS_TIMINGS[i]["estimated_duration"];
    jobsData[i].durationwithBreaks = JOBS_TIMINGS[i]["durationwithBreaks"];
};

module.exports = jobsData;

